import Order from '../models/Order.js';
import Product from '../models/Product.js';

export const createOrder = async (req, res) => {
  try {
    const { customerInfo, items, subtotal, shippingCost, tax, totalAmount, paymentMethod, customerNotes } = req.body;

    // Validation
    if (!customerInfo || !items || items.length === 0) {
      return res.status(400).json({ success: false, message: 'Customer info and items are required' });
    }

    // Validate all products and stock BEFORE creating order
    for (const item of items) {
      const product = await Product.findById(item.product);
      if (!product) {
        return res.status(404).json({ 
          success: false, 
          message: `Product not found: ${item.productName}` 
        });
      }
      if (product.stock < item.quantity) {
        return res.status(400).json({ 
          success: false, 
          message: `Insufficient stock for ${product.title || product.name}. Available: ${product.stock}` 
        });
      }
    }

    // ✅ Create order (orderNumber will be auto-generated by pre-save hook)
    const order = await Order.create({
      customerInfo,
      items,
      subtotal,
      shippingCost: shippingCost || 0,
      tax: tax || 0,
      totalAmount,
      paymentMethod: paymentMethod || 'cash_on_delivery',
      customerNotes: customerNotes || '',
      // Set payment status based on payment method
      paymentStatus: paymentMethod === 'cash_on_delivery' ? 'pending' : 'pending'
    });

    // ✅ Deduct stock ONLY after successful order creation
    for (const item of items) {
      await Product.findByIdAndUpdate(
        item.product, 
        { $inc: { stock: -item.quantity } },
        { new: true }
      );
    }

    // Populate product details for response
    const populatedOrder = await Order.findById(order._id).populate('items.product');

    res.status(201).json({ 
      success: true, 
      message: 'Order created successfully', 
      order: populatedOrder 
    });
  } catch (error) {
    console.error('❌ Error creating order:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to create order', 
      error: error.message 
    });
  }
};

export const getAllOrders = async (req, res) => {
  try {
    const { status, limit = 50, page = 1 } = req.query;
    const query = status ? { status } : {};
    const skip = (page - 1) * limit;

    const orders = await Order.find(query)
      .populate('items.product')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);
    
    const total = await Order.countDocuments(query);

    res.json({ 
      success: true, 
      orders, 
      pagination: { 
        total, 
        page: parseInt(page), 
        pages: Math.ceil(total / limit),
        limit: parseInt(limit)
      } 
    });
  } catch (error) {
    console.error('❌ Error fetching orders:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to fetch orders', 
      error: error.message 
    });
  }
};

export const getOrderById = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id).populate('items.product');
    
    if (!order) {
      return res.status(404).json({ 
        success: false, 
        message: 'Order not found' 
      });
    }
    
    res.json({ success: true, order });
  } catch (error) {
    console.error('❌ Error fetching order:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to fetch order', 
      error: error.message 
    });
  }
};

export const getOrdersByEmail = async (req, res) => {
  try {
    const orders = await Order.find({ 'customerInfo.email': req.params.email })
      .populate('items.product')
      .sort({ createdAt: -1 });
    
    res.json({ success: true, orders, count: orders.length });
  } catch (error) {
    console.error('❌ Error fetching orders by email:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to fetch orders', 
      error: error.message 
    });
  }
};

export const updateOrderStatus = async (req, res) => {
  try {
    const { status, trackingNumber, adminNotes } = req.body;
    const validStatuses = ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'];
    
    if (status && !validStatuses.includes(status)) {
      return res.status(400).json({ 
        success: false, 
        message: `Invalid status. Valid statuses: ${validStatuses.join(', ')}` 
      });
    }

    const order = await Order.findById(req.params.id);
    
    if (!order) {
      return res.status(404).json({ 
        success: false, 
        message: 'Order not found' 
      });
    }

    // ✅ If cancelling order, restore stock
    if (status === 'cancelled' && order.status !== 'cancelled') {
      for (const item of order.items) {
        await Product.findByIdAndUpdate(
          item.product, 
          { $inc: { stock: item.quantity } }
        );
      }
    }

    // Update order
    const updateData = {};
    if (status) updateData.status = status;
    if (trackingNumber) updateData.trackingNumber = trackingNumber;
    if (adminNotes) updateData.adminNotes = adminNotes;

    const updatedOrder = await Order.findByIdAndUpdate(
      req.params.id, 
      updateData, 
      { new: true, runValidators: true }
    ).populate('items.product');

    res.json({ 
      success: true, 
      message: 'Order updated successfully', 
      order: updatedOrder 
    });
  } catch (error) {
    console.error('❌ Error updating order:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to update order', 
      error: error.message 
    });
  }
};

export const deleteOrder = async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    
    if (!order) {
      return res.status(404).json({ 
        success: false, 
        message: 'Order not found' 
      });
    }

    // ✅ Restore stock if order was not cancelled (meaning stock was deducted)
    if (order.status !== 'cancelled') {
      for (const item of order.items) {
        await Product.findByIdAndUpdate(
          item.product, 
          { $inc: { stock: item.quantity } }
        );
      }
    }

    await Order.findByIdAndDelete(req.params.id);
    
    res.json({ 
      success: true, 
      message: 'Order deleted successfully' 
    });
  } catch (error) {
    console.error('❌ Error deleting order:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to delete order', 
      error: error.message 
    });
  }
};

export const getOrderStats = async (req, res) => {
  try {
    const totalOrders = await Order.countDocuments();
    const pendingOrders = await Order.countDocuments({ status: 'pending' });
    const confirmedOrders = await Order.countDocuments({ status: 'confirmed' });
    const processingOrders = await Order.countDocuments({ status: 'processing' });
    const shippedOrders = await Order.countDocuments({ status: 'shipped' });
    const deliveredOrders = await Order.countDocuments({ status: 'delivered' });
    const cancelledOrders = await Order.countDocuments({ status: 'cancelled' });

    const revenueResult = await Order.aggregate([
      { $match: { status: { $ne: 'cancelled' } } },
      { $group: { _id: null, total: { $sum: '$totalAmount' } } }
    ]);

    const paidOrdersCount = await Order.countDocuments({ paymentStatus: 'paid' });

    res.json({
      success: true,
      stats: {
        totalOrders,
        pendingOrders,
        confirmedOrders,
        processingOrders,
        shippedOrders,
        deliveredOrders,
        cancelledOrders,
        paidOrdersCount,
        totalRevenue: revenueResult[0]?.total || 0
      }
    });
  } catch (error) {
    console.error('❌ Error fetching statistics:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to fetch statistics', 
      error: error.message 
    });
  }
};